# Generated by Django 4.2.17 on 2025-01-24 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('genre', models.CharField(max_length=50)),
                ('runtime', models.IntegerField(help_text='Runtime in minutes')),
                ('posters', models.ImageField(default='movies/kill.JPG', upload_to='posters/')),
                ('banners', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField()),
                ('rows', models.IntegerField(default=12)),
                ('columns', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('movies', models.ManyToManyField(related_name='theatres', to='bookmyticket.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_timings', to='bookmyticket.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_timings', to='bookmyticket.screen')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_timings', to='bookmyticket.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('row_start', models.IntegerField()),
                ('row_end', models.IntegerField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_category', to='bookmyticket.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookmyticket.seatcategory')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookmyticket.showtimings')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='bookmyticket.theatre'),
        ),
        migrations.AddConstraint(
            model_name='showtimings',
            constraint=models.UniqueConstraint(fields=('theatre', 'screen', 'show_time', 'date'), name='unique_show_time_per_screen'),
        ),
        migrations.AddConstraint(
            model_name='seatcategory',
            constraint=models.UniqueConstraint(fields=('screen', 'category_name'), name='unique_seat_category_per_screen'),
        ),
    ]
