# Generated by Django 3.1.3 on 2024-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('runtime', models.IntegerField(help_text='Runtime in minutes')),
                ('image', models.ImageField(upload_to='movies/')),
            ],
        ),
    ]
