# Generated by Django 4.2.17 on 2025-02-01 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmbooking',
            name='number_of_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmbooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='confirmbooking',
            name='seat_numbers',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='confirmbooking',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_booking', to='bookmyticket.showtimings'),
        ),
    ]
