# Generated by Django 4.2.17 on 2025-01-12 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket', '0003_showtimings_unique_show_time_per_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='showtimings',
            name='unique_show_time_per_screen',
        ),
        migrations.AddField(
            model_name='showtimings',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='showtimings',
            constraint=models.UniqueConstraint(fields=('theatre', 'screen', 'show_time', 'date'), name='unique_show_time_per_screen'),
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookmyticket.showtimings'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show', 'row', 'column')},
        ),
    ]
