# Generated by Django 4.2.17 on 2025-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket', '0004_seat_remove_showtimings_unique_show_time_per_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=2),
        ),
    ]
