# Generated by Django 4.2.17 on 2025-01-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket', '0005_alter_seat_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='showtimings',
            name='columns',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='showtimings',
            name='rows',
            field=models.IntegerField(default=12),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
