# Generated by Django 4.2.17 on 2025-01-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket', '0006_alter_seat_unique_together_showtimings_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_row', models.IntegerField()),
                ('end_row', models.IntegerField(blank=True, null=True)),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmyticket.seatcategory')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmyticket.theatre')),
            ],
        ),
        migrations.AddField(
            model_name='theatre',
            name='seat_category',
            field=models.ManyToManyField(through='bookmyticket.SeatConfiguration', to='bookmyticket.seatcategory'),
        ),
    ]
